### ISSUE TITLE
Guile format command error

### ISSUE THREAD

**Issue by k3zaa** [ecrips/webaisleriot#4]
The Guile format procedure output is "#f" in the first example below. The second example is ok.

(display (format #f "hello world ~a xxx" "joe")) ===> #f

(display (format "welcome to earth ~a xxx" "fred")) ===> "welcome to earth fred"

See Guile docs re: format and simple-format.

This problem makes the js version of aisleriot freecell fail in get-hint et.al. when using the original create-help-list code.

I've attached the fix which ignores the 1st arg if #f in v13 of aisleriot.js. I didn't know how to send along another update since issue 2 is still open and the earlier aisleriot.js is still in the repository.
[aisleriot.js.txt](https://github.com/ecrips/webaisleriot/files/3526342/aisleriot.js.txt)

**Comment by k3zaa** [comment]
The format procedure is used in hint-move the aisleriot api.scm for the "c" version.

(define (hint-move from-slot from-slot-count to-slot)
  (if (= from-slot to-slot)
      (list 0 (format #f (hint-get-dest-format to-slot (list-tail (get-cards to-slot) from-slot-count)) (get-name (get-nth-card from-slot from-slot-count))))
      (list 0 (format #f (hint-get-dest-format to-slot (get-cards to-slot)) (get-name (get-nth-card from-slot from-slot-count))))))

**Comment by ecrips** [comment]
It looks like the version of `format` without the `dest` argument is deprecated. GNOME/aisleriot@7a22eecceea9157a8912c89834a3bf7cb2512734 fixes up the usage in `spider.scm` to pass the extra argument.

It's probably best therefore to drop support for the deprecated version and simply update `format` to take the extra `dest` argument (checking that it is `#f` because that's all we support). Along with integrating the update to `spider.scm` of course.

Btw, if you've got a bunch of updates you want to make there's no need to bump the version number each time. It's really just there for the version number on http://ecrips.co.uk/aisleriot/aisleriot.html - ideally it wouldn't be hard coded in the file but would be generated from the tags in the repository, but I never worked out a good way to do that.

**Comment by k3zaa** [comment]
Cool! What I was working on was to use the entire source from the 'c' version unmodified. I made a bunch of updates to my copy of sol.scm so it was the same as the api.scm in the 'c' version. I had a difficult time trying to figure out various bugs in my copies of the guile code. I finally worked out how to log lotsa stuff from Guile without disturbing the original code. I did so by redirecting the calls to guile aisleriot/freecell guile procedures to wrappers that did the logging. I've put a copy of this method in the attachment if you'd like to see it....go to the end of the code.
[freecell.scm.txt](https://github.com/ecrips/webaisleriot/files/3527121/freecell.scm.txt)
